#ifndef __RAZOR_ENGINE_MAIN_HEADER_FILE
#define __RAZOR_ENGINE_MAIN_HEADER_FILE

typedef enum {
    RZ_SUCCESS = 0,

    RZ_ERROR_GENERIC = 1,
    RZ_ERROR_INVALID_ARGUMENT = 2,
    RZ_ERROR_OUT_OF_MEMORY = 3,
    RZ_ERROR_NOT_IMPLEMENTED = 4,
    
    RZ_ERROR_FILE_NOT_FOUND = 5,
    RZ_ERROR_FILE_READ_ERROR = 6,
    RZ_ERROR_FILE_WRITE_ERROR = 7,

    RZ_ERROR_INTERNAL_DEPENDENCY_ERROR = 8,
    RZ_ERROR_INTERNAL_INVALID_STATE = 9,

    RZ_NOT_INITIALIZED = 10,
    RZ_ALREADY_INITIALIZED = 11,
} RzResult;

#endif